---
# Kubernetes version
kube_version: v1.30.0

# Networking
kube_network_plugin: calico
kube_pods_subnet: 192.168.0.0/16
kube_service_addresses: 10.233.0.0/18

# DNS
dns_mode: coredns
enable_nodelocaldns: true

# Container runtime
container_manager: containerd

# Cluster settings
cluster_name: salon-k8s-cluster
kube_proxy_mode: ipvs

# Kubelet settings
kubelet_max_pods: 110

# Enable metrics server
metrics_server_enabled: true

# Calico settings
calico_ipip_mode: "Always"
calico_vxlan_mode: "Never"
calico_network_backend: bird

# Download settings
download_run_once: false
download_localhost: false
