name: Infrastructure

on:
  workflow_dispatch:   # This allows manual run
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_runner_token: ${{ secrets.RUNNER_TOKEN }}

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Check Terraform version
      working-directory: terraform
      run: terraform version

    - name: Terraform Init
      working-directory: terraform
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.BUCKET_NAME }}" 
          
#    - name: Terraform Force Unlock
#      working-directory: terraform
#      run: terraform force-unlock -force 916dbd11-f9bd-bc04-b6e1-62834d384707

    - name: Terraform Format
      working-directory: terraform
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out=tfplan # Saves the plan to a file
    
#    - name: Terraform Destroy
#      working-directory: terraform
#      run: terraform destroy -auto-approve # Destroys created resources

#     OPTIONAL â€” only run manually!
    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Export Terraform output
      if: github.event_name == 'workflow_dispatch'
      working-directory: terraform
      run: terraform output -json > tf.json

    - name: Terraform output ASG
      id: asg
      working-directory: terraform
      run: |
        ASG_NAME=$(terraform output -raw asg_name 2>/dev/null)
        echo "ASG_NAME=${ASG_NAME}" >> $GITHUB_ENV

    - name: Generate inventory
      if: github.event_name == 'workflow_dispatch'
      working-directory: terraform
      env:
        ASG_NAME: ${{ env.asg_name }}
      run: |
        bash generate_inventory.sh salon-app "$ASG_NAME" 4
    
    - name: Upload inventory
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: kubespray-inventory
        path: kubespray/inventory/mycluster

      


  kubespray:
    if: github.event_name == 'workflow_dispatch'
    needs: infra
    runs-on: [self-hosted, kubespray-runner]
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Download inventory
        uses: actions/download-artifact@v4
        with:
          name: kubespray-inventory
          path: kubespray/inventory

      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install -y python3-pip ansible sshpass
          pip3 install -r kubespray/requirements.txt

      - name: Run Kubespray
        run: |
          ansible-playbook \
            -i kubespray/inventory/mycluster/hosts.yaml \
            --become --become-user=root \
            kubespray/cluster.yml


