name: Infrastructure

on:
  workflow_dispatch:   # This allows manual run
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::024955634588:role/salon-GitHubActionsInfraRole
        aws-region: ap-south-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Check Terraform version
      working-directory: terraform
      run: terraform version

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

#    - name: Terraform Force Unlock
#      working-directory: terraform
#      run: terraform force-unlock -force c91518ea-768c-caec-2f18-f0fe02eebe47

    - name: Terraform Format
      working-directory: terraform
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out=tfplan # Saves the plan to a file
    
#    - name: Terraform Destroy
#      working-directory: terraform
#      run: terraform destroy -auto-approve # Destroys created resources

#     OPTIONAL â€” only run manually!
    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'
      working-directory: terraform
      run: terraform apply -auto-approve tfplan
